---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creating EC2 server
Parameters:
  InstanceType:
    Description: 'Webserver instance type'
    Type: String
    Default: t2.micro

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  EnvironmentType:
    Description: 'Provide environment name'
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - uat
    - prod
  EmployeeName:
    Description: 'Provide Employee name'
    Type: String
  Date:
    Description: 'Provide Current Date'
    Type: Number

Resources:
  Instance01:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      Tags:
      - Key: Name
        Value: !Join ['-', ['webserver', !Ref EnvironmentType] ]
      - Key: CreatedBy
        Value: !Ref EmployeeName
      - Key: CreatedDate
        Value: !Ref Date
  Instance02:
     Type: 'AWS::EC2::Instance'
     Properties:
       ImageId: !Ref LatestAmiId
       InstanceType: !Ref InstanceType
       Tags:
       - Key: Name
         Value: !Join ['-', ['appserver', !Ref EnvironmentType] ]
       - Key: CreatedBy
         Value: !Ref EmployeeName
       - Key: CreatedDate
         Value: !Ref Date
  Instance03:
     Type: 'AWS::EC2::Instance'
     Properties:
       ImageId: !Ref LatestAmiId
       InstanceType: !Ref InstanceType
       Tags:
       - Key: Name
         Value: !Join ['-', ['dbserver', !Ref EnvironmentType] ]
       - Key: CreatedBy
         Value: !Ref EmployeeName
       - Key: CreatedDate
         Value: !Ref Date
